compile-sass:
	sass sass/styles/theme.sass:static/css/style.css --load-path sass/node_modules/milligram/src

keep-compiling-sass:
	sass --watch sass/styles/theme.sass:static/css/style.css --load-path sass/node_modules/milligram/src
